# Spring Boot 配置
server.port=11050
server.servlet.context-path=/

# 线程池配置
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=10
server.tomcat.max-connections=8192

# Spring 配置
spring.main.allow-bean-definition-overriding=true

# 日志配置
spring.output.ansi.enabled=always

# JVM 线程相关配置
spring.jmx.enabled=false
management.endpoints.jmx.exposure.exclude=*

# 日志级别配置
logging.level.root=WARN
logging.level.exmo.cy=WARN
logging.pattern.console=%msg%n

# 文件上传配置
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 数据库配置 (H2)
spring.datasource.url=jdbc:h2:file:./data/cymcserver;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate配置
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Hibernate SQL日志
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=warn

# H2数据库配置
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 静态资源配置
spring.web.resources.static-locations=classpath:/static/,classpath:/
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true